jdbcUrl = jdbc:postgresql://ec2-34-246-227-219.eu-west-1.compute.amazonaws.com:5432/d1a9ijue9vti5c
driverClassName = org.postgresql.Driver
dataSource.user = khnnyqqcozccbd
dataSource.password = d602caa0eb96012323090a0bd53e480acbbb969dc8bdf2180d7aa6cb8ca299d8