version: '3'
services:
  server:
    build: server/
    container_name: tomcat-container
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    build: db/
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=chpok
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
